### ISSUE TITLE
How to get session id

### ISSUE THREAD

**Issue by grigno** [heroku/simple-salesforce#107]
I'm sorry for the stupid question. 
Where/how can I get the session_id for the authentication without username and password?

**Comment by demianbrecht** [comment]
@grigno I'll need to understand what you're after a little better. What, exactly, are you trying to do? Are you trying to get a session ID for your currently active session? Through simple-salesforce, through a browser or something else?

**Comment by grigno** [comment]
Throught simple-salesforce I'm trying to do that:

sf = Salesforce(instance='na1.salesforce.com', session_id='')

I don't understand where i can find the session_id valute to pass to Salesforce. 

I have tried the example with username pwd and user token and everthing works good:
sf = Salesforce(username='myemail@example.com', password='password', security_token='token')

So, my question is simple: can i authenticate without username and pwd?

Thank you

**Comment by demianbrecht** [comment]
session_id is a result of authenticating a user. For example:

```
sf = Salesforce(username=<...>, password=<...>, security_token=<...>)
sf.session_id
u'<...>'
```

simple-salesforce currently only supports SOAP authentication (username/password). If you're looking at going through an OAuth 2.0 flow, you could use an OAuth client and use the resulting token as the session_id to feed into simple-salesforce. See Salesforce's [Understand Authentication](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_understanding_authentication.htm) docs for more details around the non-SOAP authentication flows.

So to answer your question, using only simple-salesforce, you cannot authenticate without a username and password. You can, however, use another authentication mechanism and pass the resulting session_id into simple_salesforce:

```sf = Salesforce(instance=<...>, session_id=<...>)```

Does that answer your question?

**Comment by grigno** [comment]
Ok, thank you for the explanantion, got it.
