### ISSUE TITLE
Result Error

### ISSUE THREAD

**Issue by CreativExit** [heroku/simple-salesforce#56]
Hi i newbie in Python i use this code but have this error:

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Use this code and create the contact in SF but dont have the result:

contact = sf.Contact.create({'LastName':'Smith','Email':'example@example.com'})
return contact

Thanks

**Comment by nickcatal** [comment]
Is this still happening?

**Comment by CreativExit** [comment]
Is working Now

Thanks
