### ISSUE TITLE
Eror with LIKE Query

### ISSUE THREAD

**Issue by pranto157** [heroku/simple-salesforce#73]
Hey Guys, 
I am using `LIKE` Operator for my query, but getting error, Also didn't found any example of usage of `LIKE` query - 

```
responses = sf.query_all("SELECT Name, Access_Key__c, Image_Vendor__c FROM Opportunity WHERE Image_Vendor__c LIKE 'Getty%'")
```
Error
```
Malformed request https://na9.salesforce.com/services/data/v29.0/query/?q=SELECT+Name%2C+Access_Key__c%2C+Image_Vendor__c+FROM+Opportunity+WHERE+Image_Vendor__c+LIKE+%27Getty%25%27. Response content: [{u'errorCode': u'INVALID_QUERY_FILTER_OPERATOR', u'message': u"\nImage_Vendor__c FROM Opportunity WHERE Image_Vendor__c LIKE 'Getty%'\n                                       ^\nERROR at Row:1:Column:68\ninvalid operator on multipicklist field"}]
```
Can anyone help ?

**Comment by greeny88** [comment]
Have you tried encoding the percent sign?

http://salesforce.stackexchange.com/questions/818/can-you-use-the-like-operator-in-soql-queries-via-the-rest-api

**Comment by demianbrecht** [comment]
Hey @pranto157, did @greeny88's response help you sort out the issue?

**Comment by pranto157** [comment]
oh sorry to mentioned that was solved. @demianbrecht. closing. Thanks @greeny88

**Comment by demianbrecht** [comment]
Cheers!
