### ISSUE TITLE
Add Accept-Encoding: gzip as a standard header

### ISSUE THREAD

**Issue by gcobr** [heroku/simple-salesforce#80]
Dear developers,

Do you think it would be OK to add Accept-Encoding: gzip a standard HTTP header in every request against Salesforce?

Python's requests library is capable of handling gzipped responses, and Salesforce can easily zip them  if we add the above-mentioned header.

https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_rest_compression.htm

I think this would be a great optimization as it would save a lot of bandwidth.

If you agree, I can send you a pull request with that change.

**Comment by demianbrecht** [comment]
Apologies for the delayed response.

I'm not sure that this should be default behavior. It's always a trade-off between CPU and bandwidth and making the assumption that bandwidth conservation should take priority is not one that I'd be in favor of making. Also, it could cause backwards incompatibility issues: If existing clients are not expecting gzipped content, either in their front end servers or application code, it would break their code.

That said, what I *would* be in favor of is reusing sessions between a ``Salesforce`` instance and ``SFType`` (which currently isn't the case). That would at least allow you to define a requests ``Session`` with default ``Accept-Encoding: gzip`` headers that would then be re-used on each subsequent request (along with other session attributes).

**Comment by demianbrecht** [comment]
I'll close this issue for now, if you feel like tackling shared sessions, feel free to open a PR :)
