### ISSUE TITLE
Expose methods other than GET via restful API

### ISSUE THREAD

**Issue by demianbrecht** [heroku/simple-salesforce#96]
Currently, `Salesforce.restful` only allows for `get` API calls. There should be a mechanism that allows a user to use other HTTP methods as well.

Reported by @babakh.

**Comment by Trii** [comment]
The bigger problem is that some methods use `requests` on their own instead of using `_call_salesforce` like the rest of the codebase. #54 also has the same issue.

**Comment by demianbrecht** [comment]
@Trii: I might be missing something, but #54 uses `self.request` which is an instance of `requests.Session`, not `requests` directly (unless that's what you're referring to). Is there elsewhere that I'm missing where `requests` is used directly? The response handling should be generalized between #54 and `Salesforce.restful` though.

There is another issue in that `SFType` and `Salesforce` don't share sessions, but that's captured in #91.

**Comment by Trii** [comment]
I was referring more to mixed use of the `requests.Session` instance vs the internal `_call_salesforce` wrapper. For consistency, everything should use `_call_salesforce`, and `_call_salesforce` should use the `requests.Session`
