### ISSUE TITLE
INVALID_LOGIN: Invalid username or password, locked out or Self-Service portal is not enabled

### ISSUE THREAD

**Issue by michaelguse** [heroku/simple-salesforce#99]
I am using the OrgAssessment tool from Babak Hosseinzadeh and I am receiving an INVALID_LOGIN failure when trying to login to Org62.

Below is the error message that is being provided when I run 'python SFDC_OrgAssess_Main.py'

```
Traceback (most recent call last):
  File "SFDC_OrgAssess_Main.py", line 64, in <module>
    org62 = Salesforce(username=Org62_user, password=Org62_pwd, organizationId='00D000000000062', version='35.0')
  File "/Users/mguse/anaconda/lib/python3.5/site-packages/simple_salesforce-0.68.1-py3.5.egg/simple_salesforce/api.py", line 108, in __init__
  File "/Users/mguse/anaconda/lib/python3.5/site-packages/simple_salesforce-0.68.1-py3.5.egg/simple_salesforce/login.py", line 129, in SalesforceLogin
simple_salesforce.login.SalesforceAuthenticationFailed: INVALID_LOGIN: Invalid username or password, locked out or Self-Service portal is not enabled
```

I am using version 0.68.1 of simple_salesforce in conjunction with the OrgAssessment tool.

I initially worked with Babak on resolving this issue, as it was working for him and other users, but we could not find any user mistake on my end (I double/triple-checked my user parameters and logged them as well). I then opened a ticket in Concierge for this, but they were not able to find a resolution for it  and pointed me to the CORE SCM group in GUS. But I don't think that group could be of any help with this either.

Somehow I think the reference to "... Self-Service portal is not enabled" in the failure message might hint at something?

I am able to run the OrgAssessment tool just fine when commenting out the login code for Org62. 

```
if pkg_resources.get_distribution('simple_salesforce').version.startswith("0.68.0"):
	sf = Salesforce(username=username, password=password, security_token=security_token, sandbox=sandbox, sf_version='35.0')
	org62 = Salesforce(username=Org62_user, password=Org62_pwd, organizationId='00D000000000062', sf_version='35.0')
else:
	sf = Salesforce(username=username, password=password, security_token=security_token, sandbox=sandbox, version='35.0')
	org62 = Salesforce(username=Org62_user, password=Org62_pwd, organizationId='00D000000000062', version='35.0')
```

That means the login to my customers org with using the security token is working ok, but when using the login into Org62 with use of the OrganizationId it fails for me.

Not sure where else to go at this point and hope this is something you might have come across in the past.

**Comment by demianbrecht** [comment]
Closing this issue as discussed offline.
